
pip install opencv-python flask flask[async] Pillow torch torchvision pydantic githubkit tqdm

# 使用官方 Python 3 镜像
FROM python:3.10

# 设置工作目录
WORKDIR /app/nailongremove_http_api

# 安装必要的包
RUN pip install --no-cache-dir opencv-python flask flask[async] Pillow torch torchvision pydantic githubkit tqdm

# 复制当前目录下的所有文件到容器中
COPY . /app


# 暴露应用运行的端口（如果需要）
# EXPOSE 8081

# 运行应用
CMD ["python", "-m", "nailongremove_http_api.http"]
