# 使用官方 Python 3 镜像
FROM python:3.10

pip install pysocks

# 复制代理环境变量
ARG http_proxy
ARG https_proxy

ENV HTTP_PROXY=${http_proxy}
ENV HTTPS_PROXY=${https_proxy}

# 设置工作目录
WORKDIR /app

# 安装必要的包
RUN pip install --upgrade pip
RUN pip install --no-cache-dir opencv-python flask flask[async] Pillow torch torchvision pydantic githubkit tqdm
RUN pip install --no-cache-dir requests opencv-python-headless httpx[socks]

# 复制当前目录下的所有文件到容器中
COPY . /app


# 暴露应用运行的端口（如果需要）
EXPOSE 8081

# 运行应用
CMD ["python", "-m", "http_main"]
